### ISSUE TITLE
Is anyone know to solve this (Duplicate column name)

### ISSUE THREAD

**Issue by pranalighalme** [PUCSD-LiveHealth/studentMGT#12]
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, studentMgt
Running migrations:
  Applying studentMgt.0002_auto_20180815_1548...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 88, in database_forwards
    field,
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 48, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 445, in add_field
    self.execute(sql, params)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/pranu/lh/djangoENV/djangoENV/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1060, "Duplicate column name 'exam_name'")

**Comment by pranalighalme** [comment]
Hello guys i got a solution..
