### ISSUE TITLE
MultiValueDictKeyError 

### ISSUE THREAD

**Issue by pranalighalme** [PUCSD-LiveHealth/studentMGT#24]
August 20, 2018 - 05:20:03
Django version 1.11.15, using settings 'PUCSD_LiveHealth.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[20/Aug/2018 05:20:18] "GET /render_add_attendance/ HTTP/1.1" 200 4958
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/morrisjs/morris.css HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/jquery/dist/jquery.min.js HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/metisMenu/dist/metisMenu.min.js HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/morrisjs/morris.min.js HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/raphael/raphael-min.js HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/js/morris-data.js HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/dist/js/sb-admin-2.js HTTP/1.1" 304 0
[20/Aug/2018 05:20:18] "GET /static/assets/dist/css/timeline.css HTTP/1.1" 200 3423
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 121200
[20/Aug/2018 05:20:18] "GET /static/assets/dist/css/sb-admin-2.css HTTP/1.1" 200 5602
[20/Aug/2018 05:20:18] "GET /static/assets/js/attendance.js HTTP/1.1" 200 3193
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/metisMenu/dist/metisMenu.min.css HTTP/1.1" 200 781
[20/Aug/2018 05:20:18] "GET /static/assets/bower_components/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 21984
[OrderedDict([('student_id', 1), ('user_id', OrderedDict([('user_id', 1), ('user_name', u'pranali@gmail.com'), ('password', u'pranu'), ('is_active', True), ('user_type', 1)])), ('parent_id', None), ('fname', u'nilesh'), ('lname', u'nikam'), ('contact', u'892389909')]), OrderedDict([('student_id', 2), ('user_id', OrderedDict([('user_id', 2), ('user_name', u'priya@gmail.com'), ('password', u'priya'), ('is_active', True), ('user_type', 2)])), ('parent_id', None), ('fname', u'nikita'), ('lname', u'neal'), ('contact', u'8600176747')]), OrderedDict([('student_id', 3), ('user_id', OrderedDict([('user_id', 2), ('user_name', u'priya@gmail.com'), ('password', u'priya'), ('is_active', True), ('user_type', 2)])), ('parent_id', None), ('fname', u'nimish'), ('lname', u'jog'), ('contact', u'890128900')]), OrderedDict([('student_id', 4), ('user_id', OrderedDict([('user_id', 2), ('user_name', u'priya@gmail.com'), ('password', u'priya'), ('is_active', True), ('user_type', 2)])), ('parent_id', None), ('fname', u'nikhil'), ('lname', u'patil'), ('contact', u'890128900')])]
[20/Aug/2018 05:20:18] "GET /student_attendance_list/ HTTP/1.1" 200 773
Internal Server Error: /add_entry_in_attendance/
Traceback (most recent call last):
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/testing/lh/studentMGT/PUCSD_LiveHealth/studentMgt/decorators.py", line 47, in wrap
    return function(request, *args, **kwargs)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/home/testing/lh/studentMGT/PUCSD_LiveHealth/studentMgt/views.py", line 45, in add_entry_in_attendance
    attObj.attendance_data = request.data['attendance_data']
  File "/home/testing/lh/djangoENV/local/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "u'attendance_data'"

Can anyone help me out to solve this problem.

**Comment by vishal1026** [comment]
Check the name of fields in model file.

**Comment by pranalighalme** [comment]
No actually the problem in json file for sending data and it solved thank you
